### ISSUE TITLE
It is not possible to set the algorithm 'ivector'

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.bio.face#2]
Since the bob.bio.gmm > 2.0.1 the ```bob.bio.algorithm``` resource called ```ivector``` doesn't exists anymore. 

Now there are 3 variants called ```ivector-cosine```, ```ivector-plda```, and ```ivector-lda-wccn-plda```.

An update is necessary in the baseline.py script in order to reflect in theses modifications.
Basically is necesary to update this line https://github.com/bioidiap/bob.bio.face/blob/master/bob/bio/face/script/baselines.py#L33

**Comment by siebenkopf** [comment]
Which one of the variants correspond to the original ``ivector`` baseline? Maybe, in a first glance, we could just use this one instead: 
https://github.com/bioidiap/bob.bio.face/blob/master/bob/bio/face/script/baselines.py#L155

In fact, the ``baselines.py`` is meant to only give a fast way to run baseline experiments. It is not meant to be all-including. So, I don't see the need of having different variants of I-Vectors inside that script. If you want to use them, use the ``verify.py`` (or its parallelized version ``verify_ivector.py``) instead.

**Comment by tiagofrepereira2012** [comment]
The original '''ivector''' baseline is with the cosine distance ('''ivector-cosine''').
I think we should link with this one.
