### ISSUE TITLE
Travis pip install --upgrade numpy may not be the best

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.bio.face#3]
I have found that this package does a `pip install --upgrade numpy` (and other packages). For those standard packages, I think running with `--upgrade` is not a good choice.

We have wheels that are pre-compiled against the numpy version which is already pre-installed on Travis virtualenvs. If you issue an `--upgrade`, it may create conflicts between the numpy version installed and that with which our SciPy wheel was compiled against.

As a suggestion, I'd completely remove this line and let the requirements to be satisfied (automatically) with the next pip installs which follow this line. If that does not work because of test requirements, I'd setup a "test.txt" requirements file and do a simple `pip install <our-idiap-wheel-repo> -r text.txt` to make sure those are installed properly.

I'm not sure other packages are the same, but we should apply the same strategy everywhere.

**Comment by siebenkopf** [comment]
You are totally right. Some time ago I was playing around with some options on Travis as it wasn't working that time. Now, we have found another solution, but some of the packages might contain some residuals of my tests. 

I will update this package as soon as I am at work. Whenever you see such inconsistencies in other packages, feel free to correct them. 

Enjoy!
